// ============================================================
// OTM — Fixture Manifest (Schema v1.1)
// CJS module. Typed registry of every fixture in this corpus;
// consumed by fixturesMeta.test.ts.
//
// STANDING PRINCIPLE (Decisions Log): the corpus is
// mechanism-comprehensive, not combinatorial — one fixture per
// distinct failure/behavior mechanism, no cross-products of field
// values.
//
// Valid fixtures are paired <slug>.row.json / <slug>.domain.json
// (hydration rules in the handoff §3); invalid fixtures are
// row-only and carry 'rejects' (constraint id) + 'expectedError'.
// Retention/sync variants come from retentionFactory.ts and are
// registered programmatically (inline, variantOf) — never as
// hand-copied files.
//
// GENERATED by the Phase 4.1 fixtures generator; edit fixtures by
// regenerating, or keep manual edits consistent with the JSON files
// (fixturesMeta.test.ts enforces sync either way).
// ============================================================

import { TableName } from './constraints';
import {
  makeRetentionBase,
  makeRetentionVariants,
  RetentionVariant,
} from './retentionFactory';

export interface FixtureFiles {
  row: string;
  domain?: string;
}

export interface EnumCoverage {
  constraintId: string;
  value: string | number;
}

export interface FixtureEntry {
  id: string;
  table: TableName;
  kind: 'valid' | 'invalid';
  mechanism: string;
  /** Paths relative to backend/tests/fixtures/. Absent for inline factory variants. */
  files?: FixtureFiles;
  /** In-memory fixture content for factory-produced variants. */
  inline?: { row: Record<string, unknown>; domain?: Record<string, unknown> };
  coversEnumValues?: EnumCoverage[];
  /** Constraint id (see constraints.ts) this invalid fixture violates. */
  rejects?: string;
  expectedError?: string;
  variantOf?: string;
}

const STATIC_ENTRIES: readonly FixtureEntry[] = [
  {
    "id": "comms_log:inbound-email-base",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Base row: inbound email via outlook push; action_required + hard time sensitivity.",
    "files": {
      "row": "comms_log/inbound-email-base.row.json",
      "domain": "comms_log/inbound-email-base.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "CL-CHK-PROVIDER",
        "value": "outlook"
      },
      {
        "constraintId": "CL-CHK-CHANNEL",
        "value": "email"
      },
      {
        "constraintId": "CL-CHK-DIRECTION",
        "value": "inbound"
      },
      {
        "constraintId": "CL-CHK-IDEMPOTENCY-PROVENANCE",
        "value": "provider_id"
      },
      {
        "constraintId": "CL-CHK-TRIAGE-LABEL",
        "value": "action_required"
      },
      {
        "constraintId": "CL-CHK-TIME-SENSITIVITY",
        "value": "hard"
      },
      {
        "constraintId": "CL-CHK-IS-SYNCED-01",
        "value": 1
      }
    ]
  },
  {
    "id": "comms_log:outbound-email-base",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Base row: outbound email; delivery lifecycle state sent.",
    "files": {
      "row": "comms_log/outbound-email-base.row.json",
      "domain": "comms_log/outbound-email-base.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "CL-CHK-DIRECTION",
        "value": "outbound"
      },
      {
        "constraintId": "CL-CHK-TRIAGE-LABEL",
        "value": "data_to_log"
      },
      {
        "constraintId": "CL-CHK-TIME-SENSITIVITY",
        "value": "none"
      },
      {
        "constraintId": "CL-CHK-DELIVERY-STATE",
        "value": "sent"
      }
    ]
  },
  {
    "id": "comms_log:inbound-sms-base",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Base row: inbound SMS via twilio; awareness_only + soft; device already marked informational; not yet synced.",
    "files": {
      "row": "comms_log/inbound-sms-base.row.json",
      "domain": "comms_log/inbound-sms-base.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "CL-CHK-PROVIDER",
        "value": "twilio"
      },
      {
        "constraintId": "CL-CHK-CHANNEL",
        "value": "sms"
      },
      {
        "constraintId": "CL-CHK-TRIAGE-LABEL",
        "value": "awareness_only"
      },
      {
        "constraintId": "CL-CHK-TIME-SENSITIVITY",
        "value": "soft"
      },
      {
        "constraintId": "CL-CHK-USER-ACTION",
        "value": "marked_informational"
      },
      {
        "constraintId": "CL-CHK-IS-SYNCED-01",
        "value": 0
      }
    ]
  },
  {
    "id": "comms_log:outbound-sms-base",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Base row: outbound SMS; delivery lifecycle state delivered.",
    "files": {
      "row": "comms_log/outbound-sms-base.row.json",
      "domain": "comms_log/outbound-sms-base.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "CL-CHK-DELIVERY-STATE",
        "value": "delivered"
      }
    ]
  },
  {
    "id": "comms_log:triage-data-to-log",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Triage mechanism: data_to_log on a polled yahoo email.",
    "files": {
      "row": "comms_log/triage-data-to-log.row.json",
      "domain": "comms_log/triage-data-to-log.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "CL-CHK-PROVIDER",
        "value": "yahoo"
      }
    ]
  },
  {
    "id": "comms_log:triage-unknown-sender",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Triage mechanism: unknown_sender with contact_id null; device action none.",
    "files": {
      "row": "comms_log/triage-unknown-sender.row.json",
      "domain": "comms_log/triage-unknown-sender.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "CL-CHK-TRIAGE-LABEL",
        "value": "unknown_sender"
      },
      {
        "constraintId": "CL-CHK-USER-ACTION",
        "value": "none"
      }
    ]
  },
  {
    "id": "comms_log:triage-unclear-review",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Triage mechanism: unclear_review; device dismissed it.",
    "files": {
      "row": "comms_log/triage-unclear-review.row.json",
      "domain": "comms_log/triage-unclear-review.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "CL-CHK-TRIAGE-LABEL",
        "value": "unclear_review"
      },
      {
        "constraintId": "CL-CHK-USER-ACTION",
        "value": "dismissed"
      }
    ]
  },
  {
    "id": "comms_log:orth-same-label-hard",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Label-orthogonality pair A (1/2): same triage_label (data_to_log), time_sensitivity hard.",
    "files": {
      "row": "comms_log/orth-same-label-hard.row.json",
      "domain": "comms_log/orth-same-label-hard.domain.json"
    }
  },
  {
    "id": "comms_log:orth-same-label-none",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Label-orthogonality pair A (2/2): same triage_label (data_to_log), time_sensitivity none.",
    "files": {
      "row": "comms_log/orth-same-label-none.row.json",
      "domain": "comms_log/orth-same-label-none.domain.json"
    }
  },
  {
    "id": "comms_log:orth-same-ts-action",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Label-orthogonality pair B (1/2): same time_sensitivity (soft), triage action_required.",
    "files": {
      "row": "comms_log/orth-same-ts-action.row.json",
      "domain": "comms_log/orth-same-ts-action.domain.json"
    }
  },
  {
    "id": "comms_log:orth-same-ts-datalog",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Label-orthogonality pair B (2/2): same time_sensitivity (soft), triage data_to_log.",
    "files": {
      "row": "comms_log/orth-same-ts-datalog.row.json",
      "domain": "comms_log/orth-same-ts-datalog.domain.json"
    }
  },
  {
    "id": "comms_log:provenance-content-hash-fallback",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Idempotency provenance content_hash_fallback with provider_message_id null (v1.1-B satisfied via fallback arm).",
    "files": {
      "row": "comms_log/provenance-content-hash-fallback.row.json",
      "domain": "comms_log/provenance-content-hash-fallback.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "CL-CHK-IDEMPOTENCY-PROVENANCE",
        "value": "content_hash_fallback"
      }
    ]
  },
  {
    "id": "comms_log:email-null-subject",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Email with null subject (subject is the only nullable NOT-NULL-family text column).",
    "files": {
      "row": "comms_log/email-null-subject.row.json",
      "domain": "comms_log/email-null-subject.domain.json"
    }
  },
  {
    "id": "comms_log:body-quoted-chain",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Verbatim body: quoted reply chain + signature + forwarded-message marker preserved.",
    "files": {
      "row": "comms_log/body-quoted-chain.row.json",
      "domain": "comms_log/body-quoted-chain.domain.json"
    }
  },
  {
    "id": "comms_log:body-injection-verbatim",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Verbatim body: prompt-injection-looking content stored as data, not interpreted.",
    "files": {
      "row": "comms_log/body-injection-verbatim.row.json",
      "domain": "comms_log/body-injection-verbatim.domain.json"
    }
  },
  {
    "id": "comms_log:body-unicode",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Verbatim body: emoji, RTL override, zero-width space, control char, CJK preserved byte-for-byte.",
    "files": {
      "row": "comms_log/body-unicode.row.json",
      "domain": "comms_log/body-unicode.domain.json"
    }
  },
  {
    "id": "comms_log:body-empty",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Verbatim body: empty string (distinct from NULL; body is NOT NULL).",
    "files": {
      "row": "comms_log/body-empty.row.json",
      "domain": "comms_log/body-empty.domain.json"
    }
  },
  {
    "id": "comms_log:body-whitespace",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Verbatim body: whitespace-only body preserved.",
    "files": {
      "row": "comms_log/body-whitespace.row.json",
      "domain": "comms_log/body-whitespace.domain.json"
    }
  },
  {
    "id": "comms_log:body-html-plaintext-alt",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Verbatim body: HTML form of a multipart HTML+plaintext-alternative message stored as-is.",
    "files": {
      "row": "comms_log/body-html-plaintext-alt.row.json",
      "domain": "comms_log/body-html-plaintext-alt.domain.json"
    }
  },
  {
    "id": "comms_log:body-qp-base64-decoded",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Verbatim body: decoded quoted-printable/base64 transfer-encoding form (accented + symbol chars).",
    "files": {
      "row": "comms_log/body-qp-base64-decoded.row.json",
      "domain": "comms_log/body-qp-base64-decoded.domain.json"
    }
  },
  {
    "id": "comms_log:multi-recipient",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "to_identifiers with multiple recipients (JSON array of 3).",
    "files": {
      "row": "comms_log/multi-recipient.row.json",
      "domain": "comms_log/multi-recipient.domain.json"
    }
  },
  {
    "id": "comms_log:delivery-queued",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Delivery lifecycle: outbound SMS queued.",
    "files": {
      "row": "comms_log/delivery-queued.row.json",
      "domain": "comms_log/delivery-queued.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "CL-CHK-DELIVERY-STATE",
        "value": "queued"
      }
    ]
  },
  {
    "id": "comms_log:delivery-failed",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Delivery lifecycle: outbound email failed with delivery_detail diagnostics.",
    "files": {
      "row": "comms_log/delivery-failed.row.json",
      "domain": "comms_log/delivery-failed.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "CL-CHK-DELIVERY-STATE",
        "value": "failed"
      }
    ]
  },
  {
    "id": "comms_log:delivery-fallback-fcm",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Delivery lifecycle: SMS leg failed, fallback_used with fallback_leg_used=fcm.",
    "files": {
      "row": "comms_log/delivery-fallback-fcm.row.json",
      "domain": "comms_log/delivery-fallback-fcm.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "CL-CHK-DELIVERY-STATE",
        "value": "fallback_used"
      },
      {
        "constraintId": "CL-CHK-FALLBACK-LEG",
        "value": "fcm"
      }
    ]
  },
  {
    "id": "comms_log:delivery-fallback-email",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Delivery lifecycle: SMS leg failed, fallback_used with fallback_leg_used=email.",
    "files": {
      "row": "comms_log/delivery-fallback-email.row.json",
      "domain": "comms_log/delivery-fallback-email.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "CL-CHK-FALLBACK-LEG",
        "value": "email"
      }
    ]
  },
  {
    "id": "comms_log:delivery-fallback-sms",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Delivery lifecycle: email leg failed, fallback_used with fallback_leg_used=sms.",
    "files": {
      "row": "comms_log/delivery-fallback-sms.row.json",
      "domain": "comms_log/delivery-fallback-sms.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "CL-CHK-FALLBACK-LEG",
        "value": "sms"
      }
    ]
  },
  {
    "id": "comms_log:provider-timestamp-fallback",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "provider_timestamp equals created_at (provider gave no timestamp; ingest time used).",
    "files": {
      "row": "comms_log/provider-timestamp-fallback.row.json",
      "domain": "comms_log/provider-timestamp-fallback.domain.json"
    }
  },
  {
    "id": "comms_log:identity-cross-channel-email",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Identity resolution (1/2): email row resolving to the same human as the SMS row (shared contact_id).",
    "files": {
      "row": "comms_log/identity-cross-channel-email.row.json",
      "domain": "comms_log/identity-cross-channel-email.domain.json"
    }
  },
  {
    "id": "comms_log:identity-cross-channel-sms",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Identity resolution (2/2): SMS row resolving to the same human as the email row (shared contact_id).",
    "files": {
      "row": "comms_log/identity-cross-channel-sms.row.json",
      "domain": "comms_log/identity-cross-channel-sms.domain.json"
    }
  },
  {
    "id": "comms_log:identity-archived-returns",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Identity resolution: archived contact writes in again; row still resolves to the archived contact.",
    "files": {
      "row": "comms_log/identity-archived-returns.row.json",
      "domain": "comms_log/identity-archived-returns.domain.json"
    }
  },
  {
    "id": "comms_log:identity-recycled-number",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Identity resolution: recycled phone number mis-match — number once belonged to the archived contact, now resolves to its current owner.",
    "files": {
      "row": "comms_log/identity-recycled-number.row.json",
      "domain": "comms_log/identity-recycled-number.domain.json"
    }
  },
  {
    "id": "comms_log:identity-changed-identifier",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Identity resolution: known human writing from a brand-new identifier → unresolved, contact_id null.",
    "files": {
      "row": "comms_log/identity-changed-identifier.row.json",
      "domain": "comms_log/identity-changed-identifier.domain.json"
    }
  },
  {
    "id": "comms_log:dedup-window-outside-a",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Dedup pair (1/2): first occurrence of identical content at 14:30.",
    "files": {
      "row": "comms_log/dedup-window-outside-a.row.json",
      "domain": "comms_log/dedup-window-outside-a.domain.json"
    }
  },
  {
    "id": "comms_log:dedup-window-outside-b",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Dedup pair (2/2): identical body/content_hash 11 minutes later — outside the 10-minute window, so BOTH rows are stored.",
    "files": {
      "row": "comms_log/dedup-window-outside-b.row.json",
      "domain": "comms_log/dedup-window-outside-b.domain.json"
    }
  },
  {
    "id": "comms_log:dedup-cross-provider",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Cross-provider dedup: identical content arrived via outlook and yahoo inside the window → exactly ONE row stored (this one); the yahoo copy was suppressed by the DAL.",
    "files": {
      "row": "comms_log/dedup-cross-provider.row.json",
      "domain": "comms_log/dedup-cross-provider.domain.json"
    }
  },
  {
    "id": "comms_log:ack-pending",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Device-field state: user_acknowledged_at / user_action_taken both null (pre-acknowledgement).",
    "files": {
      "row": "comms_log/ack-pending.row.json",
      "domain": "comms_log/ack-pending.domain.json"
    }
  },
  {
    "id": "comms_log:ack-populated",
    "table": "comms_log",
    "kind": "valid",
    "mechanism": "Device-field state: post-acknowledgement — user_acknowledged_at set, user_action_taken requested_draft_reply.",
    "files": {
      "row": "comms_log/ack-populated.row.json",
      "domain": "comms_log/ack-populated.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "CL-CHK-USER-ACTION",
        "value": "requested_draft_reply"
      }
    ]
  },
  {
    "id": "contacts:internal-two-identifier",
    "table": "contacts",
    "kind": "valid",
    "mechanism": "Internal contact with two identifiers (email + phone) across two channels.",
    "files": {
      "row": "contacts/internal-two-identifier.row.json",
      "domain": "contacts/internal-two-identifier.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "CT-CHK-STATUS",
        "value": "active"
      },
      {
        "constraintId": "CT-CHK-IS-INTERNAL-01",
        "value": 1
      },
      {
        "constraintId": "CT-CHK-IS-SYNCED-01",
        "value": 1
      }
    ]
  },
  {
    "id": "contacts:internal-email-only",
    "table": "contacts",
    "kind": "valid",
    "mechanism": "Internal contact, email-only; tone_level at the 10 ceiling.",
    "files": {
      "row": "contacts/internal-email-only.row.json",
      "domain": "contacts/internal-email-only.domain.json"
    }
  },
  {
    "id": "contacts:external-vendor",
    "table": "contacts",
    "kind": "valid",
    "mechanism": "External vendor contact (active); referenced by most comms_log fixtures.",
    "files": {
      "row": "contacts/external-vendor.row.json",
      "domain": "contacts/external-vendor.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "CT-CHK-IS-INTERNAL-01",
        "value": 0
      }
    ]
  },
  {
    "id": "contacts:external-archived",
    "table": "contacts",
    "kind": "valid",
    "mechanism": "External contact in archived status (target of identity-archived-returns).",
    "files": {
      "row": "contacts/external-archived.row.json",
      "domain": "contacts/external-archived.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "CT-CHK-STATUS",
        "value": "archived"
      }
    ]
  },
  {
    "id": "contacts:external-returned",
    "table": "contacts",
    "kind": "valid",
    "mechanism": "External contact end-state after archived→returned: active again, prior status recorded in recognition_metadata.",
    "files": {
      "row": "contacts/external-returned.row.json",
      "domain": "contacts/external-returned.domain.json"
    }
  },
  {
    "id": "contacts:external-dismissed",
    "table": "contacts",
    "kind": "valid",
    "mechanism": "External contact in dismissed status; not yet synced.",
    "files": {
      "row": "contacts/external-dismissed.row.json",
      "domain": "contacts/external-dismissed.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "CT-CHK-STATUS",
        "value": "dismissed"
      },
      {
        "constraintId": "CT-CHK-IS-SYNCED-01",
        "value": 0
      }
    ]
  },
  {
    "id": "contacts:external-role-mailbox",
    "table": "contacts",
    "kind": "valid",
    "mechanism": "External role mailbox (dispatch@); tone_level at the 0 floor.",
    "files": {
      "row": "contacts/external-role-mailbox.row.json",
      "domain": "contacts/external-role-mailbox.domain.json"
    }
  },
  {
    "id": "contacts:external-lookalike",
    "table": "contacts",
    "kind": "valid",
    "mechanism": "External lookalike: identifier is a near-duplicate of external-role-mailbox (dispatchh@ vs dispatch@).",
    "files": {
      "row": "contacts/external-lookalike.row.json",
      "domain": "contacts/external-lookalike.domain.json"
    }
  },
  {
    "id": "contacts:promoted-internal",
    "table": "contacts",
    "kind": "valid",
    "mechanism": "External→internal promotion end-state: is_internal_channel now 1, promotion recorded in recognition_metadata.",
    "files": {
      "row": "contacts/promoted-internal.row.json",
      "domain": "contacts/promoted-internal.domain.json"
    }
  },
  {
    "id": "contacts:near-name-a",
    "table": "contacts",
    "kind": "valid",
    "mechanism": "Near-name pair (1/2): display_name \"Sam Carter\".",
    "files": {
      "row": "contacts/near-name-a.row.json",
      "domain": "contacts/near-name-a.domain.json"
    }
  },
  {
    "id": "contacts:near-name-b",
    "table": "contacts",
    "kind": "valid",
    "mechanism": "Near-name pair (2/2): display_name \"Sam Carters\" — one character apart from near-name-a.",
    "files": {
      "row": "contacts/near-name-b.row.json",
      "domain": "contacts/near-name-b.domain.json"
    }
  },
  {
    "id": "contacts:alias-rich",
    "table": "contacts",
    "kind": "valid",
    "mechanism": "Alias-rich recognition_metadata (aliases, signature names, free-text note).",
    "files": {
      "row": "contacts/alias-rich.row.json",
      "domain": "contacts/alias-rich.domain.json"
    }
  },
  {
    "id": "contacts:cross-channel-human",
    "table": "contacts",
    "kind": "valid",
    "mechanism": "Contact backing the identity cross-channel pair: one human, email + SMS identifiers.",
    "files": {
      "row": "contacts/cross-channel-human.row.json",
      "domain": "contacts/cross-channel-human.domain.json"
    }
  },
  {
    "id": "contacts:recycled-number-owner",
    "table": "contacts",
    "kind": "valid",
    "mechanism": "Current owner of a recycled phone number that previously belonged to external-archived.",
    "files": {
      "row": "contacts/recycled-number-owner.row.json",
      "domain": "contacts/recycled-number-owner.domain.json"
    }
  },
  {
    "id": "contacts:phone-e164",
    "table": "contacts",
    "kind": "valid",
    "mechanism": "Identifier normalization: phone stored in E.164-style compact form.",
    "files": {
      "row": "contacts/phone-e164.row.json",
      "domain": "contacts/phone-e164.domain.json"
    }
  },
  {
    "id": "contacts:phone-national",
    "table": "contacts",
    "kind": "valid",
    "mechanism": "Identifier normalization: phone stored in national short form.",
    "files": {
      "row": "contacts/phone-national.row.json",
      "domain": "contacts/phone-national.domain.json"
    }
  },
  {
    "id": "contacts:phone-extension",
    "table": "contacts",
    "kind": "valid",
    "mechanism": "Identifier normalization: phone with extension suffix.",
    "files": {
      "row": "contacts/phone-extension.row.json",
      "domain": "contacts/phone-extension.domain.json"
    }
  },
  {
    "id": "contacts:phone-punctuation",
    "table": "contacts",
    "kind": "valid",
    "mechanism": "Identifier normalization: phone with dot punctuation variant.",
    "files": {
      "row": "contacts/phone-punctuation.row.json",
      "domain": "contacts/phone-punctuation.domain.json"
    }
  },
  {
    "id": "contacts:email-case-variant",
    "table": "contacts",
    "kind": "valid",
    "mechanism": "Identifier normalization: mixed-case email preserved as received.",
    "files": {
      "row": "contacts/email-case-variant.row.json",
      "domain": "contacts/email-case-variant.domain.json"
    }
  },
  {
    "id": "contacts:email-plus-addressing",
    "table": "contacts",
    "kind": "valid",
    "mechanism": "Identifier normalization: plus-addressed email.",
    "files": {
      "row": "contacts/email-plus-addressing.row.json",
      "domain": "contacts/email-plus-addressing.domain.json"
    }
  },
  {
    "id": "contacts:email-whitespace-wrapped",
    "table": "contacts",
    "kind": "valid",
    "mechanism": "Identifier normalization: whitespace-wrapped email preserved as received.",
    "files": {
      "row": "contacts/email-whitespace-wrapped.row.json",
      "domain": "contacts/email-whitespace-wrapped.domain.json"
    }
  },
  {
    "id": "idempotency_keys:provider-id-key",
    "table": "idempotency_keys",
    "kind": "valid",
    "mechanism": "provider_id key with +90d expiry (2026-06-05 → 2026-09-03); keys the inbound-email-base row.",
    "files": {
      "row": "idempotency_keys/provider-id-key.row.json",
      "domain": "idempotency_keys/provider-id-key.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "IK-CHK-KEY-TYPE",
        "value": "provider_id"
      },
      {
        "constraintId": "IK-CHK-PROVIDER",
        "value": "outlook"
      },
      {
        "constraintId": "IK-CHK-IS-SYNCED-01",
        "value": 1
      }
    ]
  },
  {
    "id": "idempotency_keys:content-hash-key",
    "table": "idempotency_keys",
    "kind": "valid",
    "mechanism": "content_hash key with +24h expiry; linked_message_id populated (FK to provenance-content-hash-fallback).",
    "files": {
      "row": "idempotency_keys/content-hash-key.row.json",
      "domain": "idempotency_keys/content-hash-key.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "IK-CHK-KEY-TYPE",
        "value": "content_hash"
      },
      {
        "constraintId": "IK-CHK-PROVIDER",
        "value": "yahoo"
      }
    ]
  },
  {
    "id": "idempotency_keys:window-outside-first",
    "table": "idempotency_keys",
    "kind": "valid",
    "mechanism": "10-minute-window pair (1/2): first sighting of the duplicate content at 14:30; +24h expiry.",
    "files": {
      "row": "idempotency_keys/window-outside-first.row.json",
      "domain": "idempotency_keys/window-outside-first.domain.json"
    }
  },
  {
    "id": "idempotency_keys:window-outside-second",
    "table": "idempotency_keys",
    "kind": "valid",
    "mechanism": "10-minute-window pair (2/2): second sighting at 14:41 — OUTSIDE the window, so a second comms_log row and key row are stored.",
    "files": {
      "row": "idempotency_keys/window-outside-second.row.json",
      "domain": "idempotency_keys/window-outside-second.domain.json"
    }
  },
  {
    "id": "idempotency_keys:window-inside-suppressed",
    "table": "idempotency_keys",
    "kind": "valid",
    "mechanism": "Second sighting INSIDE the 10-minute window (10:00 key, duplicate at 10:04): suppressed — no second comms_log row or key row exists; this key absorbed it. linked_message_id null (fallback content, message purged later).",
    "files": {
      "row": "idempotency_keys/window-inside-suppressed.row.json",
      "domain": "idempotency_keys/window-inside-suppressed.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "IK-CHK-PROVIDER",
        "value": "twilio"
      },
      {
        "constraintId": "IK-CHK-IS-SYNCED-01",
        "value": 0
      }
    ]
  },
  {
    "id": "thread_mappings:rfc5322-message-id",
    "table": "thread_mappings",
    "kind": "valid",
    "mechanism": "Mapping by RFC 5322 Message-ID → the inbound-email-base thread.",
    "files": {
      "row": "thread_mappings/rfc5322-message-id.row.json",
      "domain": "thread_mappings/rfc5322-message-id.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "TM-CHK-IDENTIFIER-TYPE",
        "value": "rfc5322_message_id"
      },
      {
        "constraintId": "TM-CHK-PROVIDER",
        "value": "outlook"
      },
      {
        "constraintId": "TM-CHK-IS-SYNCED-01",
        "value": 1
      }
    ]
  },
  {
    "id": "thread_mappings:provider-conversation-id",
    "table": "thread_mappings",
    "kind": "valid",
    "mechanism": "Mapping by provider conversation id → the same thread as the RFC 5322 mapping (two identifier types, one thread).",
    "files": {
      "row": "thread_mappings/provider-conversation-id.row.json",
      "domain": "thread_mappings/provider-conversation-id.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "TM-CHK-IDENTIFIER-TYPE",
        "value": "provider_conversation_id"
      }
    ]
  },
  {
    "id": "thread_mappings:phone-pair",
    "table": "thread_mappings",
    "kind": "valid",
    "mechanism": "Mapping by phone pair → the inbound-sms-base thread.",
    "files": {
      "row": "thread_mappings/phone-pair.row.json",
      "domain": "thread_mappings/phone-pair.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "TM-CHK-IDENTIFIER-TYPE",
        "value": "phone_pair"
      },
      {
        "constraintId": "TM-CHK-PROVIDER",
        "value": "twilio"
      }
    ]
  },
  {
    "id": "thread_mappings:chain-msg-2",
    "table": "thread_mappings",
    "kind": "valid",
    "mechanism": "Multi-row chain (1/2): second message of a reply chain mapping to the shared thread_key.",
    "files": {
      "row": "thread_mappings/chain-msg-2.row.json",
      "domain": "thread_mappings/chain-msg-2.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "TM-CHK-PROVIDER",
        "value": "yahoo"
      }
    ]
  },
  {
    "id": "thread_mappings:chain-msg-3",
    "table": "thread_mappings",
    "kind": "valid",
    "mechanism": "Multi-row chain (2/2): third message of the reply chain mapping to the SAME thread_key.",
    "files": {
      "row": "thread_mappings/chain-msg-3.row.json",
      "domain": "thread_mappings/chain-msg-3.domain.json"
    }
  },
  {
    "id": "thread_mappings:same-subject-conv-a",
    "table": "thread_mappings",
    "kind": "valid",
    "mechanism": "Same-subject pair (1/2): first conversation with subject \"Invoice\" → thread_key tk-subj-a.",
    "files": {
      "row": "thread_mappings/same-subject-conv-a.row.json",
      "domain": "thread_mappings/same-subject-conv-a.domain.json"
    }
  },
  {
    "id": "thread_mappings:same-subject-conv-b",
    "table": "thread_mappings",
    "kind": "valid",
    "mechanism": "Same-subject pair (2/2): unrelated conversation with the same subject → DIFFERENT thread_key tk-subj-b.",
    "files": {
      "row": "thread_mappings/same-subject-conv-b.row.json",
      "domain": "thread_mappings/same-subject-conv-b.domain.json"
    }
  },
  {
    "id": "thread_mappings:broken-chain-reply",
    "table": "thread_mappings",
    "kind": "valid",
    "mechanism": "Broken chain: reply arrived without References/In-Reply-To → starts a NEW thread_key.",
    "files": {
      "row": "thread_mappings/broken-chain-reply.row.json",
      "domain": "thread_mappings/broken-chain-reply.domain.json"
    }
  },
  {
    "id": "thread_mappings:subject-changed-mid-thread",
    "table": "thread_mappings",
    "kind": "valid",
    "mechanism": "Subject changed mid-thread: References intact, so the mapping keeps the chain thread_key despite the new subject.",
    "files": {
      "row": "thread_mappings/subject-changed-mid-thread.row.json",
      "domain": "thread_mappings/subject-changed-mid-thread.domain.json"
    }
  },
  {
    "id": "thread_mappings:group-sms-participants",
    "table": "thread_mappings",
    "kind": "valid",
    "mechanism": "Group SMS with 3+ participants: phone_pair identifier is the sorted pipe-joined participant set.",
    "files": {
      "row": "thread_mappings/group-sms-participants.row.json",
      "domain": "thread_mappings/group-sms-participants.domain.json"
    }
  },
  {
    "id": "thread_mappings:orphan-mapping",
    "table": "thread_mappings",
    "kind": "valid",
    "mechanism": "Orphan mapping: thread_key with no comms_log rows (messages purged) → purge-eligible mapping.",
    "files": {
      "row": "thread_mappings/orphan-mapping.row.json",
      "domain": "thread_mappings/orphan-mapping.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "TM-CHK-IS-SYNCED-01",
        "value": 0
      }
    ]
  },
  {
    "id": "polling_state:cold-start",
    "table": "polling_state",
    "kind": "valid",
    "mechanism": "Cold start: cursor and last_polled_at both null (account registered, never polled).",
    "files": {
      "row": "polling_state/cold-start.row.json",
      "domain": "polling_state/cold-start.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "PS-CHK-PROVIDER",
        "value": "yahoo"
      },
      {
        "constraintId": "PS-CHK-IS-SYNCED-01",
        "value": 0
      }
    ]
  },
  {
    "id": "polling_state:mid-stream",
    "table": "polling_state",
    "kind": "valid",
    "mechanism": "Mid-stream: cursor carries uidValidity + lastSeenUid; last_polled_at set.",
    "files": {
      "row": "polling_state/mid-stream.row.json",
      "domain": "polling_state/mid-stream.domain.json"
    },
    "coversEnumValues": [
      {
        "constraintId": "PS-CHK-IS-SYNCED-01",
        "value": 1
      }
    ]
  },
  {
    "id": "polling_state:uidvalidity-changed",
    "table": "polling_state",
    "kind": "valid",
    "mechanism": "uidValidity changed on the server → cursor reset story: new uidValidity, lastSeenUid back to 0.",
    "files": {
      "row": "polling_state/uidvalidity-changed.row.json",
      "domain": "polling_state/uidvalidity-changed.domain.json"
    }
  },
  {
    "id": "device_comms_log:dv-pushed",
    "table": "device_comms_log",
    "kind": "valid",
    "mechanism": "Device mirror: row pushed from backend — is_synced=1, device-writable fields still null.",
    "files": {
      "row": "device_comms_log/dv-pushed.row.json",
      "domain": "device_comms_log/dv-pushed.domain.json"
    }
  },
  {
    "id": "device_comms_log:dv-local-ack",
    "table": "device_comms_log",
    "kind": "valid",
    "mechanism": "Device mirror: user acknowledged locally — device-writable fields set, is_synced=0 until pushed back.",
    "files": {
      "row": "device_comms_log/dv-local-ack.row.json",
      "domain": "device_comms_log/dv-local-ack.domain.json"
    }
  },
  {
    "id": "device_comms_log:dv-post-push",
    "table": "device_comms_log",
    "kind": "valid",
    "mechanism": "Device mirror: acknowledgement pushed back to backend — device fields set AND is_synced=1.",
    "files": {
      "row": "device_comms_log/dv-post-push.row.json",
      "domain": "device_comms_log/dv-post-push.domain.json"
    }
  },
  {
    "id": "device_contacts:dv-contact-cache",
    "table": "device_contacts",
    "kind": "valid",
    "mechanism": "Device contacts read-only cache row: mirror of the backend external-vendor contact (same id), is_synced=1.",
    "files": {
      "row": "device_contacts/dv-contact-cache.row.json",
      "domain": "device_contacts/dv-contact-cache.domain.json"
    }
  },
  {
    "id": "comms_log:invalid:inbound-with-delivery-state",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "Inbound row carrying a delivery_state (delivery states are outbound-only).",
    "files": {
      "row": "comms_log/invalid/inbound-with-delivery-state.row.json"
    },
    "rejects": "CL-CHK-DIRECTION-DELIVERY",
    "expectedError": "CHECK constraint failed: comms_log direction/delivery_state pairing"
  },
  {
    "id": "comms_log:invalid:outbound-missing-delivery-state",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "Outbound row with delivery_state null (outbound must always carry a delivery state).",
    "files": {
      "row": "comms_log/invalid/outbound-missing-delivery-state.row.json"
    },
    "rejects": "CL-CHK-DIRECTION-DELIVERY",
    "expectedError": "CHECK constraint failed: comms_log direction/delivery_state pairing"
  },
  {
    "id": "comms_log:invalid:bad-enum-provider",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "provider outside the enum.",
    "files": {
      "row": "comms_log/invalid/bad-enum-provider.row.json"
    },
    "rejects": "CL-CHK-PROVIDER",
    "expectedError": "CHECK constraint failed: comms_log.provider"
  },
  {
    "id": "comms_log:invalid:bad-enum-channel",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "channel outside the enum.",
    "files": {
      "row": "comms_log/invalid/bad-enum-channel.row.json"
    },
    "rejects": "CL-CHK-CHANNEL",
    "expectedError": "CHECK constraint failed: comms_log.channel"
  },
  {
    "id": "comms_log:invalid:bad-enum-direction",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "direction outside the enum.",
    "files": {
      "row": "comms_log/invalid/bad-enum-direction.row.json"
    },
    "rejects": "CL-CHK-DIRECTION",
    "expectedError": "CHECK constraint failed: comms_log.direction"
  },
  {
    "id": "comms_log:invalid:bad-enum-provenance",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "idempotency_provenance outside the enum.",
    "files": {
      "row": "comms_log/invalid/bad-enum-provenance.row.json"
    },
    "rejects": "CL-CHK-IDEMPOTENCY-PROVENANCE",
    "expectedError": "CHECK constraint failed: comms_log.idempotency_provenance"
  },
  {
    "id": "comms_log:invalid:bad-enum-triage-label",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "triage_label outside the enum.",
    "files": {
      "row": "comms_log/invalid/bad-enum-triage-label.row.json"
    },
    "rejects": "CL-CHK-TRIAGE-LABEL",
    "expectedError": "CHECK constraint failed: comms_log.triage_label"
  },
  {
    "id": "comms_log:invalid:bad-enum-time-sensitivity",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "time_sensitivity_flag outside the enum.",
    "files": {
      "row": "comms_log/invalid/bad-enum-time-sensitivity.row.json"
    },
    "rejects": "CL-CHK-TIME-SENSITIVITY",
    "expectedError": "CHECK constraint failed: comms_log.time_sensitivity_flag"
  },
  {
    "id": "comms_log:invalid:bad-enum-delivery-state",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "delivery_state outside the enum (on an otherwise-legal outbound row).",
    "files": {
      "row": "comms_log/invalid/bad-enum-delivery-state.row.json"
    },
    "rejects": "CL-CHK-DELIVERY-STATE",
    "expectedError": "CHECK constraint failed: comms_log.delivery_state"
  },
  {
    "id": "comms_log:invalid:bad-enum-fallback-leg",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "fallback_leg_used outside the enum.",
    "files": {
      "row": "comms_log/invalid/bad-enum-fallback-leg.row.json"
    },
    "rejects": "CL-CHK-FALLBACK-LEG",
    "expectedError": "CHECK constraint failed: comms_log.fallback_leg_used"
  },
  {
    "id": "comms_log:invalid:bad-enum-user-action",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "user_action_taken outside the enum.",
    "files": {
      "row": "comms_log/invalid/bad-enum-user-action.row.json"
    },
    "rejects": "CL-CHK-USER-ACTION",
    "expectedError": "CHECK constraint failed: comms_log.user_action_taken"
  },
  {
    "id": "comms_log:invalid:duplicate-provider-message-id",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "Duplicate (provider, provider_message_id) of the inbound-email-base fixture — partial UNIQUE violation.",
    "files": {
      "row": "comms_log/invalid/duplicate-provider-message-id.row.json"
    },
    "rejects": "CL-UQ-PROVIDER-MSG-ID",
    "expectedError": "UNIQUE constraint failed: comms_log.provider, comms_log.provider_message_id"
  },
  {
    "id": "comms_log:invalid:fk-nonexistent-contact",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "contact_id points at a contact id absent from the corpus.",
    "files": {
      "row": "comms_log/invalid/fk-nonexistent-contact.row.json"
    },
    "rejects": "CL-FK-CONTACT",
    "expectedError": "FOREIGN KEY constraint failed: comms_log.contact_id → contacts.id"
  },
  {
    "id": "comms_log:invalid:provenance-provider-id-null-msg-id",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "v1.1-B: idempotency_provenance='provider_id' with provider_message_id null.",
    "files": {
      "row": "comms_log/invalid/provenance-provider-id-null-msg-id.row.json"
    },
    "rejects": "CL-CHK-PROVENANCE-PROVIDER-MSG-ID",
    "expectedError": "CHECK constraint failed: comms_log provenance requires provider_message_id"
  },
  {
    "id": "comms_log:invalid:is-synced-2",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "v1.1-A: is_synced outside {0,1}.",
    "files": {
      "row": "comms_log/invalid/is-synced-2.row.json"
    },
    "rejects": "CL-CHK-IS-SYNCED-01",
    "expectedError": "CHECK constraint failed: comms_log.is_synced IN (0,1)"
  },
  {
    "id": "comms_log:invalid:nn-id",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: id null.",
    "files": {
      "row": "comms_log/invalid/nn-id.row.json"
    },
    "rejects": "CL-NN-ID",
    "expectedError": "NOT NULL constraint failed: comms_log.id"
  },
  {
    "id": "comms_log:invalid:nn-created-at",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: created_at null.",
    "files": {
      "row": "comms_log/invalid/nn-created-at.row.json"
    },
    "rejects": "CL-NN-CREATED-AT",
    "expectedError": "NOT NULL constraint failed: comms_log.created_at"
  },
  {
    "id": "comms_log:invalid:nn-provider",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: provider null.",
    "files": {
      "row": "comms_log/invalid/nn-provider.row.json"
    },
    "rejects": "CL-NN-PROVIDER",
    "expectedError": "NOT NULL constraint failed: comms_log.provider"
  },
  {
    "id": "comms_log:invalid:nn-channel",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: channel null.",
    "files": {
      "row": "comms_log/invalid/nn-channel.row.json"
    },
    "rejects": "CL-NN-CHANNEL",
    "expectedError": "NOT NULL constraint failed: comms_log.channel"
  },
  {
    "id": "comms_log:invalid:nn-direction",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: direction null.",
    "files": {
      "row": "comms_log/invalid/nn-direction.row.json"
    },
    "rejects": "CL-NN-DIRECTION",
    "expectedError": "NOT NULL constraint failed: comms_log.direction"
  },
  {
    "id": "comms_log:invalid:nn-idempotency-provenance",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: idempotency_provenance null.",
    "files": {
      "row": "comms_log/invalid/nn-idempotency-provenance.row.json"
    },
    "rejects": "CL-NN-IDEMPOTENCY-PROVENANCE",
    "expectedError": "NOT NULL constraint failed: comms_log.idempotency_provenance"
  },
  {
    "id": "comms_log:invalid:nn-content-hash",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: content_hash null.",
    "files": {
      "row": "comms_log/invalid/nn-content-hash.row.json"
    },
    "rejects": "CL-NN-CONTENT-HASH",
    "expectedError": "NOT NULL constraint failed: comms_log.content_hash"
  },
  {
    "id": "comms_log:invalid:nn-thread-key",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: thread_key null.",
    "files": {
      "row": "comms_log/invalid/nn-thread-key.row.json"
    },
    "rejects": "CL-NN-THREAD-KEY",
    "expectedError": "NOT NULL constraint failed: comms_log.thread_key"
  },
  {
    "id": "comms_log:invalid:nn-from-identifier",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: from_identifier null.",
    "files": {
      "row": "comms_log/invalid/nn-from-identifier.row.json"
    },
    "rejects": "CL-NN-FROM-IDENTIFIER",
    "expectedError": "NOT NULL constraint failed: comms_log.from_identifier"
  },
  {
    "id": "comms_log:invalid:nn-to-identifiers",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: to_identifiers null.",
    "files": {
      "row": "comms_log/invalid/nn-to-identifiers.row.json"
    },
    "rejects": "CL-NN-TO-IDENTIFIERS",
    "expectedError": "NOT NULL constraint failed: comms_log.to_identifiers"
  },
  {
    "id": "comms_log:invalid:nn-body",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: body null.",
    "files": {
      "row": "comms_log/invalid/nn-body.row.json"
    },
    "rejects": "CL-NN-BODY",
    "expectedError": "NOT NULL constraint failed: comms_log.body"
  },
  {
    "id": "comms_log:invalid:nn-provider-timestamp",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: provider_timestamp null.",
    "files": {
      "row": "comms_log/invalid/nn-provider-timestamp.row.json"
    },
    "rejects": "CL-NN-PROVIDER-TIMESTAMP",
    "expectedError": "NOT NULL constraint failed: comms_log.provider_timestamp"
  },
  {
    "id": "comms_log:invalid:nn-triage-label",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: triage_label null.",
    "files": {
      "row": "comms_log/invalid/nn-triage-label.row.json"
    },
    "rejects": "CL-NN-TRIAGE-LABEL",
    "expectedError": "NOT NULL constraint failed: comms_log.triage_label"
  },
  {
    "id": "comms_log:invalid:nn-time-sensitivity-flag",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: time_sensitivity_flag null.",
    "files": {
      "row": "comms_log/invalid/nn-time-sensitivity-flag.row.json"
    },
    "rejects": "CL-NN-TIME-SENSITIVITY-FLAG",
    "expectedError": "NOT NULL constraint failed: comms_log.time_sensitivity_flag"
  },
  {
    "id": "comms_log:invalid:nn-is-synced",
    "table": "comms_log",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: is_synced null.",
    "files": {
      "row": "comms_log/invalid/nn-is-synced.row.json"
    },
    "rejects": "CL-NN-IS-SYNCED",
    "expectedError": "NOT NULL constraint failed: comms_log.is_synced"
  },
  {
    "id": "contacts:invalid:bad-enum-status",
    "table": "contacts",
    "kind": "invalid",
    "mechanism": "status outside the enum.",
    "files": {
      "row": "contacts/invalid/bad-enum-status.row.json"
    },
    "rejects": "CT-CHK-STATUS",
    "expectedError": "CHECK constraint failed: contacts.status"
  },
  {
    "id": "contacts:invalid:tone-level-11",
    "table": "contacts",
    "kind": "invalid",
    "mechanism": "tone_level above the 0–10 range.",
    "files": {
      "row": "contacts/invalid/tone-level-11.row.json"
    },
    "rejects": "CT-CHK-TONE-RANGE",
    "expectedError": "CHECK constraint failed: contacts.tone_level BETWEEN 0 AND 10"
  },
  {
    "id": "contacts:invalid:tone-level-negative",
    "table": "contacts",
    "kind": "invalid",
    "mechanism": "tone_level below the 0–10 range.",
    "files": {
      "row": "contacts/invalid/tone-level-negative.row.json"
    },
    "rejects": "CT-CHK-TONE-RANGE",
    "expectedError": "CHECK constraint failed: contacts.tone_level BETWEEN 0 AND 10"
  },
  {
    "id": "contacts:invalid:malformed-json-identifiers",
    "table": "contacts",
    "kind": "invalid",
    "mechanism": "identifiers holds unparseable JSON (DAL-class rejection; DB TEXT accepts it).",
    "files": {
      "row": "contacts/invalid/malformed-json-identifiers.row.json"
    },
    "rejects": "CT-DAL-IDENTIFIERS-JSON",
    "expectedError": "DAL rejection: contacts.identifiers is not valid JSON"
  },
  {
    "id": "contacts:invalid:wrong-shape-identifiers",
    "table": "contacts",
    "kind": "invalid",
    "mechanism": "identifiers holds valid JSON of the wrong shape (object, not array of {channel,value}) — DAL-class rejection.",
    "files": {
      "row": "contacts/invalid/wrong-shape-identifiers.row.json"
    },
    "rejects": "CT-DAL-IDENTIFIERS-SHAPE",
    "expectedError": "DAL rejection: contacts.identifiers must be an array of {channel,value}"
  },
  {
    "id": "contacts:invalid:is-internal-channel-2",
    "table": "contacts",
    "kind": "invalid",
    "mechanism": "v1.1-A: is_internal_channel outside {0,1}.",
    "files": {
      "row": "contacts/invalid/is-internal-channel-2.row.json"
    },
    "rejects": "CT-CHK-IS-INTERNAL-01",
    "expectedError": "CHECK constraint failed: contacts.is_internal_channel IN (0,1)"
  },
  {
    "id": "contacts:invalid:is-synced-2",
    "table": "contacts",
    "kind": "invalid",
    "mechanism": "v1.1-A: is_synced outside {0,1}.",
    "files": {
      "row": "contacts/invalid/is-synced-2.row.json"
    },
    "rejects": "CT-CHK-IS-SYNCED-01",
    "expectedError": "CHECK constraint failed: contacts.is_synced IN (0,1)"
  },
  {
    "id": "contacts:invalid:nn-id",
    "table": "contacts",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: id null.",
    "files": {
      "row": "contacts/invalid/nn-id.row.json"
    },
    "rejects": "CT-NN-ID",
    "expectedError": "NOT NULL constraint failed: contacts.id"
  },
  {
    "id": "contacts:invalid:nn-created-at",
    "table": "contacts",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: created_at null.",
    "files": {
      "row": "contacts/invalid/nn-created-at.row.json"
    },
    "rejects": "CT-NN-CREATED-AT",
    "expectedError": "NOT NULL constraint failed: contacts.created_at"
  },
  {
    "id": "contacts:invalid:nn-display-name",
    "table": "contacts",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: display_name null.",
    "files": {
      "row": "contacts/invalid/nn-display-name.row.json"
    },
    "rejects": "CT-NN-DISPLAY-NAME",
    "expectedError": "NOT NULL constraint failed: contacts.display_name"
  },
  {
    "id": "contacts:invalid:nn-channels",
    "table": "contacts",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: channels null.",
    "files": {
      "row": "contacts/invalid/nn-channels.row.json"
    },
    "rejects": "CT-NN-CHANNELS",
    "expectedError": "NOT NULL constraint failed: contacts.channels"
  },
  {
    "id": "contacts:invalid:nn-identifiers",
    "table": "contacts",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: identifiers null.",
    "files": {
      "row": "contacts/invalid/nn-identifiers.row.json"
    },
    "rejects": "CT-NN-IDENTIFIERS",
    "expectedError": "NOT NULL constraint failed: contacts.identifiers"
  },
  {
    "id": "contacts:invalid:nn-tone-level",
    "table": "contacts",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: tone_level null.",
    "files": {
      "row": "contacts/invalid/nn-tone-level.row.json"
    },
    "rejects": "CT-NN-TONE-LEVEL",
    "expectedError": "NOT NULL constraint failed: contacts.tone_level"
  },
  {
    "id": "contacts:invalid:nn-status",
    "table": "contacts",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: status null.",
    "files": {
      "row": "contacts/invalid/nn-status.row.json"
    },
    "rejects": "CT-NN-STATUS",
    "expectedError": "NOT NULL constraint failed: contacts.status"
  },
  {
    "id": "contacts:invalid:nn-is-internal-channel",
    "table": "contacts",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: is_internal_channel null.",
    "files": {
      "row": "contacts/invalid/nn-is-internal-channel.row.json"
    },
    "rejects": "CT-NN-IS-INTERNAL-CHANNEL",
    "expectedError": "NOT NULL constraint failed: contacts.is_internal_channel"
  },
  {
    "id": "contacts:invalid:nn-recognition-metadata",
    "table": "contacts",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: recognition_metadata null.",
    "files": {
      "row": "contacts/invalid/nn-recognition-metadata.row.json"
    },
    "rejects": "CT-NN-RECOGNITION-METADATA",
    "expectedError": "NOT NULL constraint failed: contacts.recognition_metadata"
  },
  {
    "id": "contacts:invalid:nn-is-synced",
    "table": "contacts",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: is_synced null.",
    "files": {
      "row": "contacts/invalid/nn-is-synced.row.json"
    },
    "rejects": "CT-NN-IS-SYNCED",
    "expectedError": "NOT NULL constraint failed: contacts.is_synced"
  },
  {
    "id": "idempotency_keys:invalid:bad-enum-key-type",
    "table": "idempotency_keys",
    "kind": "invalid",
    "mechanism": "key_type outside the enum.",
    "files": {
      "row": "idempotency_keys/invalid/bad-enum-key-type.row.json"
    },
    "rejects": "IK-CHK-KEY-TYPE",
    "expectedError": "CHECK constraint failed: idempotency_keys.key_type"
  },
  {
    "id": "idempotency_keys:invalid:bad-enum-provider",
    "table": "idempotency_keys",
    "kind": "invalid",
    "mechanism": "provider outside the enum.",
    "files": {
      "row": "idempotency_keys/invalid/bad-enum-provider.row.json"
    },
    "rejects": "IK-CHK-PROVIDER",
    "expectedError": "CHECK constraint failed: idempotency_keys.provider"
  },
  {
    "id": "idempotency_keys:invalid:duplicate-provider-key",
    "table": "idempotency_keys",
    "kind": "invalid",
    "mechanism": "Duplicate (provider, key_value) with key_type='provider_id' — partial UNIQUE violation against provider-id-key.",
    "files": {
      "row": "idempotency_keys/invalid/duplicate-provider-key.row.json"
    },
    "rejects": "IK-UQ-PROVIDER-KEY",
    "expectedError": "UNIQUE constraint failed: idempotency_keys.provider, idempotency_keys.key_value"
  },
  {
    "id": "idempotency_keys:invalid:fk-nonexistent-message",
    "table": "idempotency_keys",
    "kind": "invalid",
    "mechanism": "linked_message_id points at a comms_log id absent from the corpus.",
    "files": {
      "row": "idempotency_keys/invalid/fk-nonexistent-message.row.json"
    },
    "rejects": "IK-FK-LINKED-MESSAGE",
    "expectedError": "FOREIGN KEY constraint failed: idempotency_keys.linked_message_id → comms_log.id"
  },
  {
    "id": "idempotency_keys:invalid:is-synced-2",
    "table": "idempotency_keys",
    "kind": "invalid",
    "mechanism": "v1.1-A: is_synced outside {0,1}.",
    "files": {
      "row": "idempotency_keys/invalid/is-synced-2.row.json"
    },
    "rejects": "IK-CHK-IS-SYNCED-01",
    "expectedError": "CHECK constraint failed: idempotency_keys.is_synced IN (0,1)"
  },
  {
    "id": "idempotency_keys:invalid:nn-id",
    "table": "idempotency_keys",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: id null.",
    "files": {
      "row": "idempotency_keys/invalid/nn-id.row.json"
    },
    "rejects": "IK-NN-ID",
    "expectedError": "NOT NULL constraint failed: idempotency_keys.id"
  },
  {
    "id": "idempotency_keys:invalid:nn-key-type",
    "table": "idempotency_keys",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: key_type null.",
    "files": {
      "row": "idempotency_keys/invalid/nn-key-type.row.json"
    },
    "rejects": "IK-NN-KEY-TYPE",
    "expectedError": "NOT NULL constraint failed: idempotency_keys.key_type"
  },
  {
    "id": "idempotency_keys:invalid:nn-provider",
    "table": "idempotency_keys",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: provider null.",
    "files": {
      "row": "idempotency_keys/invalid/nn-provider.row.json"
    },
    "rejects": "IK-NN-PROVIDER",
    "expectedError": "NOT NULL constraint failed: idempotency_keys.provider"
  },
  {
    "id": "idempotency_keys:invalid:nn-key-value",
    "table": "idempotency_keys",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: key_value null.",
    "files": {
      "row": "idempotency_keys/invalid/nn-key-value.row.json"
    },
    "rejects": "IK-NN-KEY-VALUE",
    "expectedError": "NOT NULL constraint failed: idempotency_keys.key_value"
  },
  {
    "id": "idempotency_keys:invalid:nn-first-seen-at",
    "table": "idempotency_keys",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: first_seen_at null.",
    "files": {
      "row": "idempotency_keys/invalid/nn-first-seen-at.row.json"
    },
    "rejects": "IK-NN-FIRST-SEEN-AT",
    "expectedError": "NOT NULL constraint failed: idempotency_keys.first_seen_at"
  },
  {
    "id": "idempotency_keys:invalid:nn-expires-at",
    "table": "idempotency_keys",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: expires_at null.",
    "files": {
      "row": "idempotency_keys/invalid/nn-expires-at.row.json"
    },
    "rejects": "IK-NN-EXPIRES-AT",
    "expectedError": "NOT NULL constraint failed: idempotency_keys.expires_at"
  },
  {
    "id": "idempotency_keys:invalid:nn-is-synced",
    "table": "idempotency_keys",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: is_synced null.",
    "files": {
      "row": "idempotency_keys/invalid/nn-is-synced.row.json"
    },
    "rejects": "IK-NN-IS-SYNCED",
    "expectedError": "NOT NULL constraint failed: idempotency_keys.is_synced"
  },
  {
    "id": "thread_mappings:invalid:bad-enum-identifier-type",
    "table": "thread_mappings",
    "kind": "invalid",
    "mechanism": "identifier_type outside the enum.",
    "files": {
      "row": "thread_mappings/invalid/bad-enum-identifier-type.row.json"
    },
    "rejects": "TM-CHK-IDENTIFIER-TYPE",
    "expectedError": "CHECK constraint failed: thread_mappings.identifier_type"
  },
  {
    "id": "thread_mappings:invalid:bad-enum-provider",
    "table": "thread_mappings",
    "kind": "invalid",
    "mechanism": "provider outside the enum.",
    "files": {
      "row": "thread_mappings/invalid/bad-enum-provider.row.json"
    },
    "rejects": "TM-CHK-PROVIDER",
    "expectedError": "CHECK constraint failed: thread_mappings.provider"
  },
  {
    "id": "thread_mappings:invalid:duplicate-identifier",
    "table": "thread_mappings",
    "kind": "invalid",
    "mechanism": "Duplicate (identifier_type, identifier_value) of the rfc5322-message-id fixture — UNIQUE violation.",
    "files": {
      "row": "thread_mappings/invalid/duplicate-identifier.row.json"
    },
    "rejects": "TM-UQ-IDENTIFIER",
    "expectedError": "UNIQUE constraint failed: thread_mappings.identifier_type, thread_mappings.identifier_value"
  },
  {
    "id": "thread_mappings:invalid:is-synced-2",
    "table": "thread_mappings",
    "kind": "invalid",
    "mechanism": "v1.1-A: is_synced outside {0,1}.",
    "files": {
      "row": "thread_mappings/invalid/is-synced-2.row.json"
    },
    "rejects": "TM-CHK-IS-SYNCED-01",
    "expectedError": "CHECK constraint failed: thread_mappings.is_synced IN (0,1)"
  },
  {
    "id": "thread_mappings:invalid:nn-id",
    "table": "thread_mappings",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: id null.",
    "files": {
      "row": "thread_mappings/invalid/nn-id.row.json"
    },
    "rejects": "TM-NN-ID",
    "expectedError": "NOT NULL constraint failed: thread_mappings.id"
  },
  {
    "id": "thread_mappings:invalid:nn-identifier-type",
    "table": "thread_mappings",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: identifier_type null.",
    "files": {
      "row": "thread_mappings/invalid/nn-identifier-type.row.json"
    },
    "rejects": "TM-NN-IDENTIFIER-TYPE",
    "expectedError": "NOT NULL constraint failed: thread_mappings.identifier_type"
  },
  {
    "id": "thread_mappings:invalid:nn-identifier-value",
    "table": "thread_mappings",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: identifier_value null.",
    "files": {
      "row": "thread_mappings/invalid/nn-identifier-value.row.json"
    },
    "rejects": "TM-NN-IDENTIFIER-VALUE",
    "expectedError": "NOT NULL constraint failed: thread_mappings.identifier_value"
  },
  {
    "id": "thread_mappings:invalid:nn-provider",
    "table": "thread_mappings",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: provider null.",
    "files": {
      "row": "thread_mappings/invalid/nn-provider.row.json"
    },
    "rejects": "TM-NN-PROVIDER",
    "expectedError": "NOT NULL constraint failed: thread_mappings.provider"
  },
  {
    "id": "thread_mappings:invalid:nn-thread-key",
    "table": "thread_mappings",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: thread_key null.",
    "files": {
      "row": "thread_mappings/invalid/nn-thread-key.row.json"
    },
    "rejects": "TM-NN-THREAD-KEY",
    "expectedError": "NOT NULL constraint failed: thread_mappings.thread_key"
  },
  {
    "id": "thread_mappings:invalid:nn-created-at",
    "table": "thread_mappings",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: created_at null.",
    "files": {
      "row": "thread_mappings/invalid/nn-created-at.row.json"
    },
    "rejects": "TM-NN-CREATED-AT",
    "expectedError": "NOT NULL constraint failed: thread_mappings.created_at"
  },
  {
    "id": "thread_mappings:invalid:nn-is-synced",
    "table": "thread_mappings",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: is_synced null.",
    "files": {
      "row": "thread_mappings/invalid/nn-is-synced.row.json"
    },
    "rejects": "TM-NN-IS-SYNCED",
    "expectedError": "NOT NULL constraint failed: thread_mappings.is_synced"
  },
  {
    "id": "polling_state:invalid:provider-outlook-rejected",
    "table": "polling_state",
    "kind": "invalid",
    "mechanism": "provider='outlook' on the polling table — outlook is a push provider; polling_state accepts yahoo only.",
    "files": {
      "row": "polling_state/invalid/provider-outlook-rejected.row.json"
    },
    "rejects": "PS-CHK-PROVIDER",
    "expectedError": "CHECK constraint failed: polling_state.provider"
  },
  {
    "id": "polling_state:invalid:duplicate-provider-account-folder",
    "table": "polling_state",
    "kind": "invalid",
    "mechanism": "Duplicate (provider, account_identifier, folder) of the cold-start fixture — UNIQUE violation.",
    "files": {
      "row": "polling_state/invalid/duplicate-provider-account-folder.row.json"
    },
    "rejects": "PS-UQ-PROVIDER-ACCOUNT-FOLDER",
    "expectedError": "UNIQUE constraint failed: polling_state.provider, polling_state.account_identifier, polling_state.folder"
  },
  {
    "id": "polling_state:invalid:is-synced-2",
    "table": "polling_state",
    "kind": "invalid",
    "mechanism": "v1.1-A: is_synced outside {0,1}.",
    "files": {
      "row": "polling_state/invalid/is-synced-2.row.json"
    },
    "rejects": "PS-CHK-IS-SYNCED-01",
    "expectedError": "CHECK constraint failed: polling_state.is_synced IN (0,1)"
  },
  {
    "id": "polling_state:invalid:nn-id",
    "table": "polling_state",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: id null.",
    "files": {
      "row": "polling_state/invalid/nn-id.row.json"
    },
    "rejects": "PS-NN-ID",
    "expectedError": "NOT NULL constraint failed: polling_state.id"
  },
  {
    "id": "polling_state:invalid:nn-provider",
    "table": "polling_state",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: provider null.",
    "files": {
      "row": "polling_state/invalid/nn-provider.row.json"
    },
    "rejects": "PS-NN-PROVIDER",
    "expectedError": "NOT NULL constraint failed: polling_state.provider"
  },
  {
    "id": "polling_state:invalid:nn-account-identifier",
    "table": "polling_state",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: account_identifier null.",
    "files": {
      "row": "polling_state/invalid/nn-account-identifier.row.json"
    },
    "rejects": "PS-NN-ACCOUNT-IDENTIFIER",
    "expectedError": "NOT NULL constraint failed: polling_state.account_identifier"
  },
  {
    "id": "polling_state:invalid:nn-folder",
    "table": "polling_state",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: folder null.",
    "files": {
      "row": "polling_state/invalid/nn-folder.row.json"
    },
    "rejects": "PS-NN-FOLDER",
    "expectedError": "NOT NULL constraint failed: polling_state.folder"
  },
  {
    "id": "polling_state:invalid:nn-is-synced",
    "table": "polling_state",
    "kind": "invalid",
    "mechanism": "NOT NULL violation: is_synced null.",
    "files": {
      "row": "polling_state/invalid/nn-is-synced.row.json"
    },
    "rejects": "PS-NN-IS-SYNCED",
    "expectedError": "NOT NULL constraint failed: polling_state.is_synced"
  },
  {
    "id": "device_comms_log:invalid:device-write-backend-field",
    "table": "device_comms_log",
    "kind": "invalid",
    "mechanism": "Device write payload touching a backend-owned comms_log column (triage_label) alongside a legal ack write — DAL ownership rejection.",
    "files": {
      "row": "device_comms_log/invalid/device-write-backend-field.row.json"
    },
    "rejects": "DV-OWN-COMMS-BACKEND-FIELD",
    "expectedError": "DAL ownership rejection: device may write only user_acknowledged_at / user_action_taken on comms_log"
  },
  {
    "id": "device_contacts:invalid:device-write-readonly-cache",
    "table": "device_contacts",
    "kind": "invalid",
    "mechanism": "Device write payload targeting contacts at all — the device contacts cache is read-only; every device write is rejected.",
    "files": {
      "row": "device_contacts/invalid/device-write-readonly-cache.row.json"
    },
    "rejects": "DV-OWN-CONTACTS-READONLY",
    "expectedError": "DAL ownership rejection: device_contacts is a read-only cache"
  }
];

function entryFromVariant(v: RetentionVariant, variantOf?: string): FixtureEntry {
  return {
    id: `comms_log:${v.slug}`,
    table: 'comms_log',
    kind: 'valid',
    mechanism: v.mechanism,
    inline: {
      row: v.row as unknown as Record<string, unknown>,
      domain: v.domain as unknown as Record<string, unknown>,
    },
    ...(variantOf !== undefined ? { variantOf } : {}),
  };
}

const RETENTION_ENTRIES: readonly FixtureEntry[] = [
  entryFromVariant(makeRetentionBase()),
  ...makeRetentionVariants().map((v) => entryFromVariant(v, 'comms_log:retention-base')),
];

export const MANIFEST: readonly FixtureEntry[] = [...STATIC_ENTRIES, ...RETENTION_ENTRIES];
